services:
  - type: web
    name: sistema-clinica-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libreoffice libreoffice-writer libreoffice-common
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
